/**
 * Ergonomic TypeScript surface over the native napi addon.
 *
 * The native `Client` (generated by napi-rs into index.js / index.d.ts at build
 * time) exposes JSON-string methods; this wrapper provides the typed, friendly
 * API: two clients (least privilege), enums, and result types. The Rust core
 * does the real work.
 */

// The native addon. napi-rs emits `index.js` (loader) + `index.d.ts` at build.
// eslint-disable-next-line @typescript-eslint/no-var-requires
import { Client as NativeClient } from "./index.js";

export enum Backend {
  Ollama = "ollama",
  Vllm = "vllm",
  VllmOmni = "vllm-omni",
  Sglang = "sglang",
}

export enum OnDrift {
  Reconcile = "reconcile",
  Fail = "fail",
  DryRun = "dry_run",
  Warn = "warn",
  Ignore = "ignore",
}

/** A declarative workload definition (the intent handed to `ensure()`). */
export interface WorkloadSpec {
  name: string;
  slug: string;
  model: string;
  backend: Backend | string;
  project?: string;
  description?: string;
  command?: string;
  vllmVersion?: string;
  taskType?: string;
  config?: Record<string, unknown>;
  executionPolicy?: string;
  executionPolicyConfig?: Record<string, unknown>;
  workerId?: string;
  gpuResourceId?: string;
}

export interface EndpointRef {
  projectSlug: string;
  workloadSlug: string;
}

export interface TextResult {
  text: string;
  model: string;
  finishReason?: string;
  raw: unknown;
}

export interface EmbedResult {
  embeddings: number[][];
  model: string;
  raw: unknown;
}

const DEFAULT_BASE_URL = "https://api.inferencekey.com";

function env(name: string): string | undefined {
  const v = process.env[name];
  return v && v.length > 0 ? v : undefined;
}

/** Map a WorkloadSpec to the snake_case wire shape the core expects. */
function specToWire(spec: WorkloadSpec): Record<string, unknown> {
  const out: Record<string, unknown> = {
    name: spec.name,
    slug: spec.slug,
    model: spec.model,
    backend: spec.backend,
  };
  const optional: Record<string, unknown> = {
    project: spec.project,
    description: spec.description,
    command: spec.command,
    vllm_version: spec.vllmVersion,
    task_type: spec.taskType,
    config: spec.config,
    execution_policy: spec.executionPolicy,
    execution_policy_config: spec.executionPolicyConfig,
    worker_id: spec.workerId,
    gpu_resource_id: spec.gpuResourceId,
  };
  for (const [k, v] of Object.entries(optional)) {
    if (v !== undefined && v !== null) out[k] = v;
  }
  return out;
}

/** Control-plane client (`ik_sdk_` token). Provisions; no inference. */
export class ManagementClient {
  private constructor(
    private readonly native: NativeClient,
    private readonly sdkToken: string,
    private readonly project?: string,
  ) {}

  static fromEnv(opts: { baseUrl?: string; project?: string; sdkToken?: string } = {}): ManagementClient {
    const baseUrl = opts.baseUrl ?? env("INFERENCEKEY_BASE_URL") ?? DEFAULT_BASE_URL;
    const sdkToken = opts.sdkToken ?? env("INFERENCEKEY_SDK_TOKEN") ?? "";
    return new ManagementClient(new NativeClient(baseUrl), sdkToken, opts.project ?? env("INFERENCEKEY_PROJECT"));
  }

  async ensure(
    spec: WorkloadSpec,
    opts: { onDrift?: OnDrift; project?: string } = {},
  ): Promise<EndpointRef> {
    const projectId = opts.project ?? spec.project ?? this.project;
    if (!projectId) {
      throw new Error("No project configured. Set INFERENCEKEY_PROJECT, pass project, or set spec.project.");
    }
    const raw = await this.native.ensure(
      this.sdkToken,
      projectId,
      JSON.stringify(specToWire(spec)),
      opts.onDrift ?? OnDrift.Reconcile,
    );
    return JSON.parse(raw) as EndpointRef;
  }
}

/** Data-plane client. One `Endpoint` per workload, each with its own `ik_live_` key. */
export class DataClient {
  private constructor(
    private readonly native: NativeClient,
    private readonly project: string,
    private readonly defaultKey?: string,
  ) {}

  static fromEnv(opts: { baseUrl?: string; project?: string; apiKey?: string } = {}): DataClient {
    const baseUrl = opts.baseUrl ?? env("INFERENCEKEY_BASE_URL") ?? DEFAULT_BASE_URL;
    const project = opts.project ?? env("INFERENCEKEY_PROJECT") ?? "";
    return new DataClient(new NativeClient(baseUrl), project, opts.apiKey ?? env("INFERENCEKEY_API_KEY"));
  }

  endpoint(workloadSlug: string, opts: { apiKey?: string } = {}): Endpoint {
    const key = opts.apiKey ?? this.defaultKey;
    if (!key) {
      throw new Error(`No ik_live_ key for workload "${workloadSlug}". Pass apiKey or set INFERENCEKEY_API_KEY.`);
    }
    return new Endpoint(this.native, this.project, workloadSlug, key);
  }
}

/** A single workload's OpenAI-compatible endpoint, bound to one `ik_live_` key. */
export class Endpoint {
  constructor(
    private readonly native: NativeClient,
    private readonly projectSlug: string,
    readonly workloadSlug: string,
    private readonly apiKey: string,
  ) {}

  async generateText(params: {
    prompt?: string;
    messages?: { role: string; content: string }[];
    temperature?: number;
    maxTokens?: number;
  }): Promise<TextResult> {
    const wire = {
      prompt: params.prompt,
      messages: params.messages,
      temperature: params.temperature,
      max_tokens: params.maxTokens,
    };
    const raw = await this.native.generateText(
      this.projectSlug,
      this.workloadSlug,
      this.apiKey,
      JSON.stringify(wire),
    );
    return JSON.parse(raw) as TextResult;
  }

  async embed(params: { input: string | string[] }): Promise<EmbedResult> {
    const input = Array.isArray(params.input) ? params.input : [params.input];
    const raw = await this.native.embed(
      this.projectSlug,
      this.workloadSlug,
      this.apiKey,
      JSON.stringify({ input }),
    );
    return JSON.parse(raw) as EmbedResult;
  }
}
