/**
 * Ergonomic TypeScript surface over the native napi addon.
 *
 * The native `Client` (generated by napi-rs into index.js / index.d.ts at build
 * time) exposes JSON-string methods; this wrapper provides the typed, friendly
 * API: two clients (least privilege), enums, and result types. The Rust core
 * does the real work.
 */

// The native addon. napi-rs emits `index.js` (loader) + `index.d.ts` at build.
import { Client as NativeClient, ChatStream as NativeChatStream } from "./index.js";

// `as const` objects (not TS `enum`) so the file is plain type-strippable TS and
// carries no runtime enum machinery — same wire strings either way.
export const Backend = {
  Ollama: "ollama",
  Vllm: "vllm",
  VllmOmni: "vllm-omni",
  Sglang: "sglang",
} as const;
export type Backend = (typeof Backend)[keyof typeof Backend];

export const OnDrift = {
  Reconcile: "reconcile",
  Fail: "fail",
  DryRun: "dry_run",
  Warn: "warn",
  Ignore: "ignore",
} as const;
export type OnDrift = (typeof OnDrift)[keyof typeof OnDrift];

/** A declarative workload definition (the intent handed to `ensure()`). */
export interface WorkloadSpec {
  name: string;
  slug: string;
  model: string;
  backend: Backend | string;
  project?: string;
  description?: string;
  command?: string;
  vllmVersion?: string;
  taskType?: string;
  config?: Record<string, unknown>;
  executionPolicy?: string;
  executionPolicyConfig?: Record<string, unknown>;
  workerId?: string;
  gpuResourceId?: string;
}

export interface EndpointRef {
  projectSlug: string;
  workloadSlug: string;
}

export interface TextResult {
  text: string;
  model: string;
  finishReason?: string;
  raw: unknown;
}

/** One streamed chunk of a chat completion (a `chat.completion.chunk`). */
export interface TextChunk {
  /** The delta for this frame — concatenate chunks to rebuild the full reply. */
  text: string;
  /** Set only on the terminal chunk. */
  finishReason?: string;
  raw: unknown;
}

export interface EmbedResult {
  embeddings: number[][];
  model: string;
  raw: unknown;
}

const DEFAULT_BASE_URL = "https://api.inferencekey.com";

function env(name: string): string | undefined {
  const v = process.env[name];
  return v && v.length > 0 ? v : undefined;
}

/** Pause for `ms` milliseconds (used by readiness backoff). */
function sleep(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

/**
 * A readiness probe error that will never resolve by waiting: a bad/insufficient
 * credential, wrong token type, or unknown workload. The native layer renders
 * these as CoreError strings with stable prefixes, so we match on those.
 */
function isFatalReadinessError(err: unknown): boolean {
  const message = err instanceof Error ? err.message : String(err);
  return (
    message.startsWith("authentication failed") ||
    message.startsWith("permission denied") ||
    message.startsWith("not found") ||
    message.startsWith("validation error")
  );
}

// `NativeChatStream` is the type returned by the native `generateTextStream`;
// referenced here so the wrapper's `generateTextStream` is typed end-to-end.
export type { NativeChatStream };

/** Map a WorkloadSpec to the snake_case wire shape the core expects. */
function specToWire(spec: WorkloadSpec): Record<string, unknown> {
  const out: Record<string, unknown> = {
    name: spec.name,
    slug: spec.slug,
    model: spec.model,
    backend: spec.backend,
  };
  const optional: Record<string, unknown> = {
    project: spec.project,
    description: spec.description,
    command: spec.command,
    vllm_version: spec.vllmVersion,
    task_type: spec.taskType,
    config: spec.config,
    execution_policy: spec.executionPolicy,
    execution_policy_config: spec.executionPolicyConfig,
    worker_id: spec.workerId,
    gpu_resource_id: spec.gpuResourceId,
  };
  for (const [k, v] of Object.entries(optional)) {
    if (v !== undefined && v !== null) out[k] = v;
  }
  return out;
}

/** Control-plane client (`ik_sdk_` token). Provisions; no inference. */
export class ManagementClient {
  private constructor(
    private readonly native: NativeClient,
    private readonly sdkToken: string,
    private readonly project?: string,
  ) {}

  static fromEnv(opts: { baseUrl?: string; project?: string; sdkToken?: string } = {}): ManagementClient {
    const baseUrl = opts.baseUrl ?? env("INFERENCEKEY_BASE_URL") ?? DEFAULT_BASE_URL;
    const sdkToken = opts.sdkToken ?? env("INFERENCEKEY_SDK_TOKEN") ?? "";
    return new ManagementClient(new NativeClient(baseUrl), sdkToken, opts.project ?? env("INFERENCEKEY_PROJECT"));
  }

  async ensure(
    spec: WorkloadSpec,
    opts: { onDrift?: OnDrift; project?: string } = {},
  ): Promise<EndpointRef> {
    const projectId = opts.project ?? spec.project ?? this.project;
    if (!projectId) {
      throw new Error("No project configured. Set INFERENCEKEY_PROJECT, pass project, or set spec.project.");
    }
    const raw = await this.native.ensure(
      this.sdkToken,
      projectId,
      JSON.stringify(specToWire(spec)),
      opts.onDrift ?? OnDrift.Reconcile,
    );
    // The core returns the EndpointRef as snake_case JSON (`project_slug` /
    // `workload_slug`); map it to the camelCase public shape rather than a bare
    // `as` cast, which would silently leave the fields `undefined`.
    const ref = JSON.parse(raw) as { project_slug: string; workload_slug: string };
    return { projectSlug: ref.project_slug, workloadSlug: ref.workload_slug };
  }
}

/** Data-plane client. One `Endpoint` per workload, each with its own `ik_live_` key. */
export class DataClient {
  private constructor(
    private readonly native: NativeClient,
    private readonly project: string,
    private readonly defaultKey?: string,
  ) {}

  static fromEnv(opts: { baseUrl?: string; project?: string; apiKey?: string } = {}): DataClient {
    const baseUrl = opts.baseUrl ?? env("INFERENCEKEY_BASE_URL") ?? DEFAULT_BASE_URL;
    const project = opts.project ?? env("INFERENCEKEY_PROJECT") ?? "";
    return new DataClient(new NativeClient(baseUrl), project, opts.apiKey ?? env("INFERENCEKEY_API_KEY"));
  }

  endpoint(workloadSlug: string, opts: { apiKey?: string } = {}): Endpoint {
    const key = opts.apiKey ?? this.defaultKey;
    if (!key) {
      throw new Error(`No ik_live_ key for workload "${workloadSlug}". Pass apiKey or set INFERENCEKEY_API_KEY.`);
    }
    return new Endpoint(this.native, this.project, workloadSlug, key);
  }
}

/** A single workload's OpenAI-compatible endpoint, bound to one `ik_live_` key. */
export class Endpoint {
  constructor(
    private readonly native: NativeClient,
    private readonly projectSlug: string,
    readonly workloadSlug: string,
    private readonly apiKey: string,
  ) {}

  async generateText(params: {
    prompt?: string;
    messages?: { role: string; content: string }[];
    temperature?: number;
    maxTokens?: number;
  }): Promise<TextResult> {
    const wire = {
      prompt: params.prompt,
      messages: params.messages,
      temperature: params.temperature,
      max_tokens: params.maxTokens,
    };
    const raw = await this.native.generateText(
      this.projectSlug,
      this.workloadSlug,
      this.apiKey,
      JSON.stringify(wire),
    );
    // Core JSON is snake_case (`finish_reason`); map to the camelCase surface.
    const data = JSON.parse(raw) as { text: string; model: string; finish_reason?: string; raw: unknown };
    return { text: data.text, model: data.model, finishReason: data.finish_reason, raw: data.raw };
  }

  /**
   * Open a streaming chat completion, yielding one {@link TextChunk} per SSE
   * frame as tokens are produced. The connection opens eagerly (so auth /
   * validation errors throw here, not mid-iteration); chunks are then pulled
   * lazily as you iterate:
   *
   * ```ts
   * for await (const chunk of ep.generateTextStream({ prompt: "Hola" })) {
   *   process.stdout.write(chunk.text);
   * }
   * ```
   */
  async *generateTextStream(params: {
    prompt?: string;
    messages?: { role: string; content: string }[];
    temperature?: number;
    maxTokens?: number;
  }): AsyncGenerator<TextChunk, void, unknown> {
    const wire = {
      prompt: params.prompt,
      messages: params.messages,
      temperature: params.temperature,
      max_tokens: params.maxTokens,
    };
    const stream = await this.native.generateTextStream(
      this.projectSlug,
      this.workloadSlug,
      this.apiKey,
      JSON.stringify(wire),
    );
    for (;;) {
      const raw = await stream.next();
      if (raw === null) return;
      const data = JSON.parse(raw) as { text: string; finish_reason?: string; raw: unknown };
      yield { text: data.text, finishReason: data.finish_reason, raw: data.raw };
    }
  }

  /**
   * Resolve once the workload's endpoint is serving, by probing it.
   *
   * The control plane has no readiness flag, so this sends a tiny chat probe
   * and treats a transport/5xx failure as "still starting" — retrying with
   * exponential backoff up to `maxIntervalMs` — while a 401/403/404 (bad key,
   * wrong token type, unknown workload) is a real error that rejects
   * immediately. Rejects with a timeout error if `timeoutMs` elapses first.
   * Call this after `ensure()` provisions a cold worker, before streaming.
   */
  async waitUntilReady(opts: { timeoutMs?: number; intervalMs?: number; maxIntervalMs?: number } = {}): Promise<void> {
    const timeoutMs = opts.timeoutMs ?? 300_000;
    const maxIntervalMs = opts.maxIntervalMs ?? 15_000;
    const deadline = Date.now() + timeoutMs;
    let delay = opts.intervalMs ?? 2_000;
    for (;;) {
      try {
        await this.generateText({ prompt: "ping", maxTokens: 1 });
        return; // a successful completion means the worker is up.
      } catch (err) {
        // A wrong/insufficient credential or unknown workload never becomes
        // ready — surface it instead of spinning. Everything else (transport
        // error, 5xx) means the worker is likely still booting, so retry.
        if (isFatalReadinessError(err)) throw err;
        if (Date.now() >= deadline) {
          throw new Error(`workload "${this.workloadSlug}" not ready after ${Math.round(timeoutMs / 1000)}s`);
        }
        await sleep(Math.min(delay, Math.max(0, deadline - Date.now())));
        delay = Math.min(delay * 2, maxIntervalMs);
      }
    }
  }

  async embed(params: { input: string | string[] }): Promise<EmbedResult> {
    const input = Array.isArray(params.input) ? params.input : [params.input];
    const raw = await this.native.embed(
      this.projectSlug,
      this.workloadSlug,
      this.apiKey,
      JSON.stringify({ input }),
    );
    return JSON.parse(raw) as EmbedResult;
  }
}
