/**
 * Ergonomic TypeScript surface over the native napi addon.
 *
 * The native `Client` (generated by napi-rs into index.js / index.d.ts at build
 * time) exposes JSON-string methods; this wrapper provides the typed, friendly
 * API: two clients (least privilege), enums, and result types. The Rust core
 * does the real work.
 */

// The native addon. napi-rs emits `index.js` (loader) + `index.d.ts` at build.
import { Client as NativeClient, ChatStream as NativeChatStream } from "./index.js";

/** A readiness phase reported while waiting for a workload to come up. */
export type ReadinessPhase = "scheduling" | "provisioning" | "bootstrapping" | "ready" | "error";

/** One readiness progress update from `ManagementClient.waitUntilReady`. */
export interface ReadinessEvent {
  phase: ReadinessPhase;
  /** Short, printable line describing what the platform is doing. */
  message: string;
  /** Milliseconds since the wait started. */
  elapsedMs: number;
  /** Allow-listed bootstrap step (e.g. `model_load`), when applicable. */
  step?: string;
}

// `as const` objects (not TS `enum`) so the file is plain type-strippable TS and
// carries no runtime enum machinery — same wire strings either way.
export const Backend = {
  Ollama: "ollama",
  Vllm: "vllm",
  VllmOmni: "vllm-omni",
  Sglang: "sglang",
} as const;
export type Backend = (typeof Backend)[keyof typeof Backend];

export const OnDrift = {
  Reconcile: "reconcile",
  Fail: "fail",
  DryRun: "dry_run",
  Warn: "warn",
  Ignore: "ignore",
} as const;
export type OnDrift = (typeof OnDrift)[keyof typeof OnDrift];

/** A declarative workload definition (the intent handed to `ensure()`). */
export interface WorkloadSpec {
  name: string;
  slug: string;
  model: string;
  backend: Backend | string;
  project?: string;
  description?: string;
  command?: string;
  vllmVersion?: string;
  taskType?: string;
  config?: Record<string, unknown>;
  executionPolicy?: string;
  executionPolicyConfig?: Record<string, unknown>;
  workerId?: string;
  gpuResourceId?: string;
}

export interface EndpointRef {
  projectSlug: string;
  workloadSlug: string;
}

export interface TextResult {
  text: string;
  model: string;
  finishReason?: string;
  raw: unknown;
}

/** One streamed chunk of a chat completion (a `chat.completion.chunk`). */
export interface TextChunk {
  /** The delta for this frame — concatenate chunks to rebuild the full reply. */
  text: string;
  /** Set only on the terminal chunk. */
  finishReason?: string;
  raw: unknown;
}

export interface EmbedResult {
  embeddings: number[][];
  model: string;
  raw: unknown;
}

const DEFAULT_BASE_URL = "https://api.inferencekey.com";

function env(name: string): string | undefined {
  const v = process.env[name];
  return v && v.length > 0 ? v : undefined;
}

/** Ordered phases for the progress view; the index drives the step display. */
const READINESS_PHASES: ReadinessPhase[] = ["scheduling", "provisioning", "bootstrapping", "ready"];

/** The default terminal progress view. `render` paints on each readiness event;
 * `tick` repaints the same line with a freshly elapsed clock between events so
 * the seconds counter keeps moving during long waits (cold starts can take
 * minutes between server-sent events). On a non-TTY there is no clock to animate,
 * so `tick` is a no-op and each event prints one plain line. */
export interface ProgressRenderer {
  /** Paint on a new event. `elapsedMs`, when given, overrides the server's
   * `event.elapsedMs` for the on-screen clock (TTY only) so it stays monotonic
   * with `tick`'s local clock. */
  render(event: ReadinessEvent, elapsedMs?: number): void;
  tick(elapsedMs: number): void;
}

/**
 * Build the default terminal progress renderer used by `waitUntilReady`.
 *
 * On a TTY it shows a single redrawn line of phase dots with the current
 * message and elapsed time; off a TTY (CI / piped) it prints one plain line per
 * event so logs stay readable. The returned object exposes `render` (call per
 * event) and `tick` (call ~1×/s to advance the clock between events).
 */
export function makeProgressRenderer(): ProgressRenderer {
  const isTty = Boolean((process.stdout as { isTTY?: boolean }).isTTY);
  // The most recent event, retained so `tick` can repaint the same phase/message
  // with an updated clock. Cleared once we reach a terminal phase.
  let last: ReadinessEvent | undefined;
  let done = false;

  const paint = (event: ReadinessEvent, elapsedMs: number) => {
    const secs = Math.round(elapsedMs / 1000);
    const reached =
      event.phase === "error" ? READINESS_PHASES.length - 1 : READINESS_PHASES.indexOf(event.phase);
    const dots = READINESS_PHASES.map((p, i) => {
      if (event.phase === "ready" || i < reached) return `\x1b[32m●\x1b[0m`; // done
      if (i === reached) return `\x1b[36m◐\x1b[0m`; // in progress
      return `\x1b[90m○\x1b[0m`; // pending
    }).join(" ");
    const label = event.phase === "error" ? `\x1b[31m${event.message}\x1b[0m` : event.message;
    // \r returns to line start; \x1b[K clears to end of line before redraw.
    process.stdout.write(`\r\x1b[K${dots}  ${label} (${secs}s)`);
  };

  return {
    render(event: ReadinessEvent, elapsedMs?: number): void {
      if (!isTty) {
        const secs = Math.round(event.elapsedMs / 1000);
        const step = event.step ? ` [${event.step}]` : "";
        process.stdout.write(`[${secs}s] ${event.phase}${step}: ${event.message}\n`);
        return;
      }
      last = event;
      paint(event, elapsedMs ?? event.elapsedMs);
      if (event.phase === "ready" || event.phase === "error") {
        done = true;
        process.stdout.write("\n");
      }
    },
    tick(elapsedMs: number): void {
      if (!isTty || done || !last) return;
      paint(last, elapsedMs);
    },
  };
}

// `NativeChatStream` is the type returned by the native `generateTextStream`;
// referenced here so the wrapper's `generateTextStream` is typed end-to-end.
export type { NativeChatStream };

/** Map a WorkloadSpec to the snake_case wire shape the core expects. */
function specToWire(spec: WorkloadSpec): Record<string, unknown> {
  const out: Record<string, unknown> = {
    name: spec.name,
    slug: spec.slug,
    model: spec.model,
    backend: spec.backend,
  };
  const optional: Record<string, unknown> = {
    project: spec.project,
    description: spec.description,
    command: spec.command,
    vllm_version: spec.vllmVersion,
    task_type: spec.taskType,
    config: spec.config,
    execution_policy: spec.executionPolicy,
    execution_policy_config: spec.executionPolicyConfig,
    worker_id: spec.workerId,
    gpu_resource_id: spec.gpuResourceId,
  };
  for (const [k, v] of Object.entries(optional)) {
    if (v !== undefined && v !== null) out[k] = v;
  }
  return out;
}

/** Control-plane client (`ik_sdk_` token). Provisions; no inference. */
export class ManagementClient {
  private constructor(
    private readonly native: NativeClient,
    private readonly sdkToken: string,
    private readonly project?: string,
  ) {}

  static fromEnv(opts: { baseUrl?: string; project?: string; sdkToken?: string } = {}): ManagementClient {
    const baseUrl = opts.baseUrl ?? env("INFERENCEKEY_BASE_URL") ?? DEFAULT_BASE_URL;
    const sdkToken = opts.sdkToken ?? env("INFERENCEKEY_SDK_TOKEN") ?? "";
    return new ManagementClient(new NativeClient(baseUrl), sdkToken, opts.project ?? env("INFERENCEKEY_PROJECT"));
  }

  async ensure(
    spec: WorkloadSpec,
    opts: { onDrift?: OnDrift; project?: string } = {},
  ): Promise<EndpointRef> {
    const projectId = opts.project ?? spec.project ?? this.project;
    if (!projectId) {
      throw new Error("No project configured. Set INFERENCEKEY_PROJECT, pass project, or set spec.project.");
    }
    const raw = await this.native.ensure(
      this.sdkToken,
      projectId,
      JSON.stringify(specToWire(spec)),
      opts.onDrift ?? OnDrift.Reconcile,
    );
    // The core returns the EndpointRef as snake_case JSON (`project_slug` /
    // `workload_slug`); map it to the camelCase public shape rather than a bare
    // `as` cast, which would silently leave the fields `undefined`.
    const ref = JSON.parse(raw) as { project_slug: string; workload_slug: string };
    return { projectSlug: ref.project_slug, workloadSlug: ref.workload_slug };
  }

  /**
   * Delete a workload by slug. Resolves to `true` if it existed, `false` if it
   * was already gone — idempotent, so it's safe to call on shutdown/cleanup
   * without checking first.
   *
   * Cloud GPUs the autoscaler provisioned for the workload are torn down on the
   * platform (private workers are only unassigned), so deleting also stops the
   * billable capacity. Uses the `ik_sdk_` control token.
   *
   * ```ts
   * process.on("SIGINT", async () => { await mgmt.delete(slug); process.exit(0); });
   * ```
   */
  async delete(workloadSlug: string, opts: { project?: string } = {}): Promise<boolean> {
    const projectId = opts.project ?? this.project;
    if (!projectId) {
      throw new Error("No project configured. Set INFERENCEKEY_PROJECT or pass project.");
    }
    return this.native.delete(this.sdkToken, projectId, workloadSlug);
  }

  /**
   * Wait until `workloadSlug` is serving, reporting progress as the platform
   * schedules a worker, provisions a cloud GPU, and boots the runtime.
   *
   * Resolves when the platform reports the `ready` phase; rejects on an `error`
   * phase or after `timeoutMs`. By default it prints a live progress view to
   * the terminal; pass your own `onProgress` to handle events yourself, or
   * `silent: true` to suppress output. Subscribing to progress uses the
   * `ik_sdk_` control token, so this lives on the management client (no data
   * key needed).
   *
   * ```ts
   * const ref = await mgmt.ensure(spec);
   * await mgmt.waitUntilReady(ref.workloadSlug, { timeoutMs: 600_000 });
   * ```
   */
  async waitUntilReady(
    workloadSlug: string,
    opts: {
      project?: string;
      timeoutMs?: number;
      onProgress?: (event: ReadinessEvent) => void;
      silent?: boolean;
    } = {},
  ): Promise<void> {
    const projectId = opts.project ?? this.project;
    if (!projectId) {
      throw new Error("No project configured. Set INFERENCEKEY_PROJECT or pass project.");
    }
    const timeoutMs = opts.timeoutMs ?? 600_000;
    // Default render is the built-in terminal progress view, unless the caller
    // brings their own onProgress or asks for silence. The built-in view also
    // animates a clock between events (`ticker`); a caller's onProgress and the
    // silent path get events only, no clock. `renderer` is set only for the
    // built-in path; otherwise events go to `onEvent`.
    const renderer = opts.onProgress || opts.silent ? undefined : makeProgressRenderer();
    const onEvent = opts.onProgress ?? (() => {});

    const stream = await this.native.readinessEvents(this.sdkToken, projectId, workloadSlug);

    let timer: ReturnType<typeof setTimeout> | undefined;
    const timeout = new Promise<never>((_, reject) => {
      timer = setTimeout(
        () => reject(new Error(`workload "${workloadSlug}" not ready after ${Math.round(timeoutMs / 1000)}s`)),
        timeoutMs,
      );
    });

    // Advance the on-screen seconds counter ~1×/s between server events so a long
    // cold start doesn't look frozen. Keyed off a local clock (the server only
    // restamps elapsed on each event). No-op until the first event arrives, and
    // off for custom/silent renderers.
    const startedAt = Date.now();
    const ticker = renderer
      ? setInterval(() => renderer.tick(Date.now() - startedAt), 1000)
      : undefined;
    if (ticker && typeof ticker.unref === "function") ticker.unref();

    let stopped = false;
    const drive = (async () => {
      for (;;) {
        const raw = await stream.next();
        // Once the race is decided (ready / error / timeout) stop pulling so we
        // don't keep the SSE connection open past the point we care about.
        if (stopped) return;
        if (raw === null) return; // stream ended without an explicit ready
        const data = JSON.parse(raw) as { phase: ReadinessPhase; message: string; elapsed_ms: number; step?: string };
        const event: ReadinessEvent = {
          phase: data.phase,
          message: data.message,
          elapsedMs: data.elapsed_ms,
          step: data.step,
        };
        // The built-in renderer shares the ticker's local clock so the counter
        // never jumps; a caller's onProgress gets the event verbatim.
        if (renderer) renderer.render(event, Date.now() - startedAt);
        else onEvent(event);
        if (event.phase === "ready") return;
        if (event.phase === "error") throw new Error(`workload "${workloadSlug}" failed to become ready: ${event.message}`);
      }
    })();

    try {
      await Promise.race([drive, timeout]);
    } finally {
      stopped = true;
      if (timer) clearTimeout(timer);
      if (ticker) clearInterval(ticker);
      // Close the native stream so the in-flight next() unblocks and the SSE
      // connection is released (otherwise it keeps the event loop alive).
      stream.close();
      drive.catch(() => {});
    }
  }
}

/** Data-plane client. One `Endpoint` per workload, each with its own `ik_live_` key. */
export class DataClient {
  private constructor(
    private readonly native: NativeClient,
    private readonly project: string,
    private readonly defaultKey?: string,
  ) {}

  static fromEnv(opts: { baseUrl?: string; project?: string; apiKey?: string } = {}): DataClient {
    const baseUrl = opts.baseUrl ?? env("INFERENCEKEY_BASE_URL") ?? DEFAULT_BASE_URL;
    const project = opts.project ?? env("INFERENCEKEY_PROJECT") ?? "";
    return new DataClient(new NativeClient(baseUrl), project, opts.apiKey ?? env("INFERENCEKEY_API_KEY"));
  }

  endpoint(workloadSlug: string, opts: { apiKey?: string } = {}): Endpoint {
    const key = opts.apiKey ?? this.defaultKey;
    if (!key) {
      throw new Error(`No ik_live_ key for workload "${workloadSlug}". Pass apiKey or set INFERENCEKEY_API_KEY.`);
    }
    return new Endpoint(this.native, this.project, workloadSlug, key);
  }
}

/** A single workload's OpenAI-compatible endpoint, bound to one `ik_live_` key. */
export class Endpoint {
  constructor(
    private readonly native: NativeClient,
    private readonly projectSlug: string,
    readonly workloadSlug: string,
    private readonly apiKey: string,
  ) {}

  async generateText(params: {
    prompt?: string;
    messages?: { role: string; content: string }[];
    temperature?: number;
    maxTokens?: number;
  }): Promise<TextResult> {
    const wire = {
      prompt: params.prompt,
      messages: params.messages,
      temperature: params.temperature,
      max_tokens: params.maxTokens,
    };
    const raw = await this.native.generateText(
      this.projectSlug,
      this.workloadSlug,
      this.apiKey,
      JSON.stringify(wire),
    );
    // Core JSON is snake_case (`finish_reason`); map to the camelCase surface.
    const data = JSON.parse(raw) as { text: string; model: string; finish_reason?: string; raw: unknown };
    return { text: data.text, model: data.model, finishReason: data.finish_reason, raw: data.raw };
  }

  /**
   * Open a streaming chat completion, yielding one {@link TextChunk} per SSE
   * frame as tokens are produced. The connection opens eagerly (so auth /
   * validation errors throw here, not mid-iteration); chunks are then pulled
   * lazily as you iterate:
   *
   * ```ts
   * for await (const chunk of ep.generateTextStream({ prompt: "Hola" })) {
   *   process.stdout.write(chunk.text);
   * }
   * ```
   */
  async *generateTextStream(params: {
    prompt?: string;
    messages?: { role: string; content: string }[];
    temperature?: number;
    maxTokens?: number;
  }): AsyncGenerator<TextChunk, void, unknown> {
    const wire = {
      prompt: params.prompt,
      messages: params.messages,
      temperature: params.temperature,
      max_tokens: params.maxTokens,
    };
    const stream = await this.native.generateTextStream(
      this.projectSlug,
      this.workloadSlug,
      this.apiKey,
      JSON.stringify(wire),
    );
    for (;;) {
      const raw = await stream.next();
      if (raw === null) return;
      const data = JSON.parse(raw) as { text: string; finish_reason?: string; raw: unknown };
      yield { text: data.text, finishReason: data.finish_reason, raw: data.raw };
    }
  }

  async embed(params: { input: string | string[] }): Promise<EmbedResult> {
    const input = Array.isArray(params.input) ? params.input : [params.input];
    const raw = await this.native.embed(
      this.projectSlug,
      this.workloadSlug,
      this.apiKey,
      JSON.stringify({ input }),
    );
    return JSON.parse(raw) as EmbedResult;
  }
}
